### ISSUE TITLE
impTest in Factory Firmware?

### ISSUE THREAD

**Issue by deldrid1** [electricimp/impTest#25]
@myurasov, have you given any thought as to how this might be used in the Factory for End of Line Testing?

I'm thinking that I can [run the tests manually](https://github.com/electricimp/impTest/blob/develop/docs/writing-tests.md#running-tests-manually) in my device code but am just about to start digesting the code for the first time and was curious if you had any suggestions that I might want to pay attention to.

**Comment by myurasov** [comment]
Austin,

Given the specifics of a factory flow, you probabaly refer to using [impUnit](https://github.com/electricimp/impUnit) framework rather than a test runner. Structuring your factory firmware as test cases makes sense in terms of development convenience and ability to formalize the factory testing as set of test cases. Currently cases run in the order of appearance in the code and there is no way to change it or skip some from the framework level. Looks like it may be valuable for factory firmware application. Please let me know if it's the case.

Side note: we believe that, while impTest can be used in some integration and E2E scenarios, it's focused is on testing the Squirrel code. However there are plans to provide ways to integrate it into more high-level flows.

Let me know if you would like the quickstart/howto session on this.

**Comment by deldrid1** [comment]
I'll take a look at impUnit and let you know how it goes - I've given it a quick look already and I think I can probably get started stealing any of your time.

One other question - are you using Node.js tools to compile your source at this point?  It looks like you are in this project but in impUnit, no such tools are included in the repo (although it does have a distribution directory so no big issue - really just a curiosity).

**Comment by myurasov** [comment]
For now framework sources are put together before the test session using [preprocessor.js](https://www.npmjs.com/package/preprocessor), which also has a cli tool. Later on there will be a standard preprocessor provided as a part of impTool that will also be used internally by impTest.

Feel free to ask questions, should you have any, we're really interested in this being tested in the wild. :)
